global using DryIoc;
global using HandyControl.Controls;
global using HandyControl.Data;
global using ImTools;
global using Prism.Commands;
global using Prism.Common;
global using Prism.Events;
global using Prism.Ioc;
global using Prism.Mvvm;
global using Prism.Regions;
global using Prism.Services.Dialogs;
global using System;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.Globalization;
global using System.Linq;
global using System.Reflection;
global using System.Windows;
global using MS.Client.BasicInfoModule.Views;
global using MS.Client.Common;
global using MessageBox = HandyControl.Controls.MessageBox;
global using Newtonsoft.Json;
global using MS.Client.Service;
global using SugarDemo.Shared;
global using MS.Client.BasicInfoModule.ViewModels;
global using MS.Client.BasicInfoModule.ViewModels.Dialogs;
global using MS.Client.BasicInfoModule.Views.Dialogs;
global using Prism.Modularity;


